name: Main 

on: [push]

jobs:
    set-nightly:
        runs-on: ubuntu-latest

        steps:
             - uses: actions/checkout@v1

             - name: Override Rust toolchain to Nightly
               run: rustup override set nightly

    build:
        needs: set-nightly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run build
              run: cargo build --verbose
    test:
        needs: set-nightly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run tests
              run: cargo test --verbose

    lint:
        needs: set-nightly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run Rustfmt
              run: cargo fmt -- --check
            
            - name: Run Clippy
              run: cargo clippy --verbose

            - name: Run Cargo check
              run: cargo check --verbose
    
    benchmark:
        needs: set-nightly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run benchmarks
              run: cargo bench --verbose

    audit:
        needs: set-nightly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run dependency security audit
              run: cargo --verbose audit

